# Generated by Django 3.2.3 on 2021-05-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=500)),
                ('techUsed', models.CharField(max_length=200)),
                ('pmonth', models.CharField(max_length=50)),
                ('pyear', models.IntegerField()),
                ('pdescrpation', models.TextField()),
                ('plink', models.CharField(max_length=500)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
